/* eslint-disable @typescript-eslint/no-explicit-any */
import fs from "fs"
import { fileURLToPath } from "url"
import path from "path"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

const localesDir = path.resolve(__dirname, "../src/locales/langs")
const outFile = path.resolve(__dirname, "../src/typings/i18n.d.ts")
const langs = fs.readdirSync(localesDir).filter((f) => fs.statSync(path.join(localesDir, f)).isDirectory())

const result: Record<string, Set<string>> = {}

fs.readdirSync(localesDir).forEach((lang) => {
  const langDir = path.join(localesDir, lang)
  if (!fs.statSync(langDir).isDirectory()) return

  fs.readdirSync(langDir).forEach((file) => {
    const ns = path.basename(file, ".json")
    const content = JSON.parse(fs.readFileSync(path.join(langDir, file), "utf-8"))

    if (!result[ns]) result[ns] = new Set()
    collectKeys(content, "", result[ns])
  })
})

function collectKeys(obj: any, prefix: string, keys: Set<string>) {
  for (const key in obj) {
    const fullKey = prefix ? `${prefix}.${key}` : key
    const value = obj[key]
    if (typeof value === "object" && value !== null && !Array.isArray(value)) {
      collectKeys(value, fullKey, keys)
    } else {
      keys.add(fullKey)
    }
  }
}

let output = `/* Auto-generated by gen-i18n-types. Do not edit manually. */\n`

output += `/* eslint-disable @typescript-eslint/no-explicit-any */\n\n`
output += `declare namespace I18nKeys {\n`

const namespaces = Object.keys(result)

namespaces.forEach((ns) => {
  const keys = Array.from(result[ns]).sort()

  output += `  type ${ns} =\n    | ${keys.map((k) => `"${k}"`).join("\n    | ")}\n\n`
})

output += `}\n`

output += `type I18nFullKey =\n  ${namespaces.map((ns) => `| \`${ns}.\${I18nKeys.${ns}}\``).join("\n  ")}\n\n`

output += `declare namespace I18n {\n`
output += `  type LangType = ${langs.map((l) => `"${l}"`).join(" | ")}\n\n`
output += `  type LangOption = {\n`
output += `    label: string\n`
output += `    key: LangType\n`
output += `  }\n\n`
output += `  type TranslateOptions<Locales extends string = LangType> = import("vue-i18n").TranslateOptions<Locales>\n\n`
output += `  interface $T {\n`
output += `    (key: I18nFullKey): string\n`
output += `    (key: I18nFullKey, plural: number, options?: TranslateOptions<LangType>): string\n`
output += `    (key: I18nFullKey, defaultMsg: string, options?: TranslateOptions<I18nFullKey>): string\n`
output += `    (key: I18nFullKey, list: unknown[], options?: TranslateOptions<I18nFullKey>): string\n`
output += `    (key: I18nFullKey, list: unknown[], plural: number): string\n`
output += `    (key: I18nFullKey, list: unknown[], defaultMsg: string): string\n`
output += `    (key: I18nFullKey, named: Record<string, unknown>, options?: TranslateOptions<LangType>): string\n`
output += `    (key: I18nFullKey, named: Record<string, unknown>, plural: number): string\n`
output += `    (key: I18nFullKey, named: Record<string, unknown>, defaultMsg: string): string\n`
output += `  }\n`
output += `}\n`

fs.mkdirSync(path.dirname(outFile), { recursive: true })
fs.writeFileSync(outFile, output)

console.log("i18n.d.ts generated!")
