/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

/* prettier-ignore */
import type { RouteComponent } from "vue-router";
/* prettier-ignore */
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

/* prettier-ignore */
import BaseLayout from "@/layouts/base-layout/index.vue";
/* prettier-ignore */
import BlankLayout from "@/layouts/blank-layout/index.vue";

/* prettier-ignore */
export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

/* prettier-ignore */
export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  home: () => import("@/views/home/index.vue"),
};
